# Generated by Django 5.1.1 on 2026-08-22 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField()),
                ('image_url', models.CharField(default='https://images.unsplash.com/photo-1488646953014-85cb44e25828?w=800&auto=format&fit=crop&q=80', max_length=500)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='cities/')),
                ('cost_index', models.CharField(choices=[('BUDGET', 'Budget ($)'), ('MODERATE', 'Moderate ($$)'), ('LUXURY', 'Luxury ($$$)')], default='MODERATE', max_length=10)),
                ('popularity_score', models.IntegerField(default=85)),
                ('latitude', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
                ('best_season', models.CharField(default='Spring & Autumn', max_length=100)),
                ('avg_daily_cost', models.DecimalField(decimal_places=2, default=120.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Cities',
                'ordering': ['-popularity_score', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(blank=True, max_length=5)),
                ('continent', models.CharField(choices=[('Europe', 'Europe'), ('Asia', 'Asia'), ('North America', 'North America'), ('South America', 'South America'), ('Africa', 'Africa'), ('Oceania', 'Oceania')], default='Europe', max_length=50)),
                ('currency', models.CharField(default='USD', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('SIGHTSEEING', 'Sightseeing & Landmarks'), ('FOOD', 'Food & Culinary Tours'), ('ADVENTURE', 'Adventure & Outdoors'), ('CULTURE', 'Culture & Museums'), ('RELAXATION', 'Relaxation & Wellness'), ('TRANSPORT', 'Transport & Transfers'), ('NIGHTLIFE', 'Nightlife & Entertainment')], default='SIGHTSEEING', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=25.0, max_digits=10)),
                ('duration_hours', models.FloatField(default=2.0)),
                ('image_url', models.CharField(blank=True, default='https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&auto=format&fit=crop&q=80', max_length=500)),
                ('rating', models.FloatField(default=4.8)),
                ('location_address', models.CharField(blank=True, max_length=300)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='destinations.city')),
            ],
            options={
                'verbose_name_plural': 'Activities',
                'ordering': ['-rating', 'name'],
            },
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='destinations.country'),
        ),
    ]
