# Generated by Django 5.1.1 on 2026-08-22 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='state_or_region',
            field=models.CharField(blank=True, default='', help_text='e.g. Gujarat, Kashmir, Himachal Pradesh, Rajasthan', max_length=100),
        ),
        migrations.AlterField(
            model_name='activity',
            name='category',
            field=models.CharField(choices=[('SIGHTSEEING', 'Sightseeing & Heritage 🏛️'), ('FOOD', 'Food & Culinary Tours 🍲'), ('ADVENTURE', 'Trekking & Snow Adventures 🏔️'), ('CULTURE', 'Culture & Festivals 🪔'), ('SPIRITUAL', 'Temples & Spiritual 🛕'), ('RELAXATION', 'Houseboats, Lakes & Wellness 🌿'), ('TRANSPORT', 'Transport & Transfers 🚆'), ('NIGHTLIFE', 'Night Markets & Cafes ☕')], default='SIGHTSEEING', max_length=20),
        ),
        migrations.AlterField(
            model_name='activity',
            name='estimated_cost',
            field=models.DecimalField(decimal_places=2, default=500.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='city',
            name='avg_daily_cost',
            field=models.DecimalField(decimal_places=2, default=3500.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='city',
            name='best_season',
            field=models.CharField(default='October - March', max_length=100),
        ),
        migrations.AlterField(
            model_name='city',
            name='cost_index',
            field=models.CharField(choices=[('BUDGET', 'Budget (₹)'), ('MODERATE', 'Moderate (₹₹)'), ('LUXURY', 'Luxury (₹₹₹)')], default='MODERATE', max_length=10),
        ),
        migrations.AlterField(
            model_name='country',
            name='continent',
            field=models.CharField(choices=[('Asia', 'Asia'), ('Europe', 'Europe'), ('North America', 'North America'), ('South America', 'South America'), ('Africa', 'Africa'), ('Oceania', 'Oceania')], default='Asia', max_length=50),
        ),
        migrations.AlterField(
            model_name='country',
            name='currency',
            field=models.CharField(default='INR', max_length=10),
        ),
    ]
