# Generated by Django 5.2.4 on 2026-05-26 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='best_time',
            field=models.CharField(default='best season', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destination',
            name='rating',
            field=models.FloatField(default=4.5),
        ),
    ]
