# Generated by Django 5.2.4 on 2026-05-27 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0003_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='destination',
        ),
        migrations.AddField(
            model_name='favorite',
            name='destination_best_time',
            field=models.CharField(default='exit', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='favorite',
            name='destination_category',
            field=models.CharField(default='general', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='favorite',
            name='destination_description',
            field=models.TextField(default='unknow'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='favorite',
            name='destination_name',
            field=models.CharField(default='unknow', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='favorite',
            name='destination_rating',
            field=models.FloatField(default=4.5),
        ),
        migrations.AddField(
            model_name='favorite',
            name='destination_region',
            field=models.CharField(default='unkonow', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='favorite',
            name='destination_state',
            field=models.CharField(default='gujarat', max_length=100),
            preserve_default=False,
        ),
    ]
