# Generated by Django 5.1.1 on 2026-08-22 07:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('USER_JOIN', 'New Traveler Joined'), ('TRIP_CREATE', 'Trip Created'), ('TRIP_CLONE', 'Trip Cloned'), ('REVIEW_POST', 'Review & Rating Added'), ('COMMENT_POST', 'Comment Added'), ('DESTINATION_EXPLORE', 'Destination Explored')], default='TRIP_CREATE', max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('reference_url', models.CharField(blank=True, max_length=300)),
                ('icon', models.CharField(default='fa-plane-departure', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
