# Generated by Django 6.0.7 on 2026-08-22 08:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("icon", models.CharField(default="compass", max_length=50)),
                ("color", models.CharField(default="#3B82F6", max_length=20)),
            ],
            options={
                "verbose_name_plural": "Activity Categories",
            },
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "cost_index",
                    models.CharField(
                        choices=[
                            ("$", "Budget ($)"),
                            ("$$", "Moderate ($$)"),
                            ("$$$", "Luxury ($$$)"),
                        ],
                        default="$$",
                        max_length=10,
                    ),
                ),
                (
                    "popularity_score",
                    models.FloatField(default=85.0, help_text="Score between 0-100"),
                ),
                ("description", models.TextField()),
                ("image_url", models.URLField(max_length=500)),
                (
                    "best_time_to_visit",
                    models.CharField(default="Spring & Autumn", max_length=100),
                ),
                (
                    "avg_daily_cost",
                    models.DecimalField(decimal_places=2, default=120.0, max_digits=10),
                ),
                ("climate_tag", models.CharField(default="Temperate", max_length=50)),
                ("latitude", models.FloatField(default=0.0)),
                ("longitude", models.FloatField(default=0.0)),
            ],
            options={
                "verbose_name_plural": "Cities",
                "ordering": ["-popularity_score", "name"],
            },
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("code", models.CharField(max_length=10, unique=True)),
                ("currency", models.CharField(default="USD", max_length=10)),
                (
                    "flag_emoji",
                    models.CharField(blank=True, default="🌍", max_length=10),
                ),
            ],
            options={
                "verbose_name_plural": "Countries",
            },
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("code", models.CharField(max_length=20, unique=True)),
                ("description", models.TextField(blank=True)),
                ("image_url", models.URLField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "estimated_cost",
                    models.DecimalField(decimal_places=2, default=30.0, max_digits=10),
                ),
                ("duration_hours", models.FloatField(default=2.5)),
                ("rating", models.FloatField(default=4.8)),
                ("image_url", models.URLField(max_length=500)),
                ("location_name", models.CharField(blank=True, max_length=200)),
                ("is_popular", models.BooleanField(default=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="travel_planner.activitycategory",
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="travel_planner.city",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Activities",
                "ordering": ["-rating", "title"],
            },
        ),
        migrations.AddField(
            model_name="city",
            name="country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cities",
                to="travel_planner.country",
            ),
        ),
        migrations.AddField(
            model_name="country",
            name="region",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="countries",
                to="travel_planner.region",
            ),
        ),
        migrations.AddField(
            model_name="city",
            name="region",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cities",
                to="travel_planner.region",
            ),
        ),
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "cover_image",
                    models.URLField(
                        blank=True,
                        default="https://images.unsplash.com/photo-1488646953014-85cb44e25828?w=800&auto=format&fit=crop&q=80",
                        max_length=500,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ongoing", "Ongoing"),
                            ("upcoming", "Up-coming"),
                            ("completed", "Completed"),
                            ("draft", "Draft"),
                        ],
                        default="upcoming",
                        max_length=20,
                    ),
                ),
                (
                    "total_budget",
                    models.DecimalField(
                        decimal_places=2, default=1500.0, max_digits=12
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=True,
                        help_text="Visible in Community and shareable via public URL",
                    ),
                ),
                ("likes_count", models.PositiveIntegerField(default=0)),
                ("copies_count", models.PositiveIntegerField(default=0)),
                ("views_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trips",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TripComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="travel_planner.trip",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trip_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="TripStop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=1)),
                ("arrival_date", models.DateField()),
                ("departure_date", models.DateField()),
                (
                    "allocated_budget",
                    models.DecimalField(decimal_places=2, default=500.0, max_digits=10),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trip_stops",
                        to="travel_planner.city",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stops",
                        to="travel_planner.trip",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "arrival_date"],
            },
        ),
        migrations.CreateModel(
            name="TripExpense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("transport", "Transport"),
                            ("stay", "Stay / Accommodation"),
                            ("activities", "Activities & Sightseeing"),
                            ("meals", "Meals & Dining"),
                            ("other", "Miscellaneous"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("description", models.CharField(max_length=250)),
                ("date", models.DateField(default=django.utils.timezone.now)),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expenses",
                        to="travel_planner.trip",
                    ),
                ),
                (
                    "trip_stop",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expenses",
                        to="travel_planner.tripstop",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="ItineraryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "cost",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("day_number", models.PositiveIntegerField(default=1)),
                ("date", models.DateField(blank=True, null=True)),
                ("start_time", models.CharField(default="10:00 AM", max_length=20)),
                ("end_time", models.CharField(default="12:30 PM", max_length=20)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("activity", "Activity / Sightseeing"),
                            ("transport", "Transport"),
                            ("stay", "Hotel / Stay"),
                            ("meal", "Food & Dining"),
                            ("other", "Other"),
                        ],
                        default="activity",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("is_completed", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=1)),
                (
                    "activity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="itinerary_items",
                        to="travel_planner.activity",
                    ),
                ),
                (
                    "trip_stop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itinerary_items",
                        to="travel_planner.tripstop",
                    ),
                ),
            ],
            options={
                "ordering": ["day_number", "order", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "bio",
                    models.TextField(
                        blank=True,
                        help_text="Additional information about traveler",
                        null=True,
                    ),
                ),
                (
                    "avatar_url",
                    models.URLField(
                        blank=True,
                        default="https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300&auto=format&fit=crop&q=80",
                        max_length=500,
                        null=True,
                    ),
                ),
                ("language_preference", models.CharField(default="en", max_length=10)),
                ("currency_preference", models.CharField(default="USD", max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SavedDestination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_by_users",
                        to="travel_planner.city",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_destinations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "city")},
            },
        ),
        migrations.CreateModel(
            name="TripLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="travel_planner.trip",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trip_likes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "trip")},
            },
        ),
    ]
