# Generated by Django 6.0.7 on 2026-08-22 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travel_planner", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PackingItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("clothing", "Clothing & Apparel"),
                            ("electronics", "Tech & Electronics"),
                            ("documents", "Travel Documents & Money"),
                            ("toiletries", "Health & Toiletries"),
                            ("activity_gear", "Activity & Adventure Gear"),
                        ],
                        default="clothing",
                        max_length=30,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("is_packed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="packing_items",
                        to="travel_planner.trip",
                    ),
                ),
            ],
            options={
                "ordering": ["category", "name"],
            },
        ),
    ]
