# Generated by Django 5.1.1 on 2026-08-22 07:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destinations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('bio', models.TextField(blank=True, default='Passionate global traveler exploring unique cultures and hidden gems.')),
                ('avatar_url', models.CharField(blank=True, default='', max_length=500)),
                ('avatar_img', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('is_email_verified', models.BooleanField(default=False)),
                ('verification_token', models.CharField(blank=True, max_length=64)),
                ('travel_style', models.CharField(choices=[('SOLO', 'Solo Explorer'), ('COUPLE', 'Romantic Getaway'), ('FAMILY', 'Family Vacation'), ('BACKPACKER', 'Backpacker / Budget'), ('LUXURY', 'Luxury & Leisure'), ('ADVENTURE', 'Adrenaline & Nature')], default='SOLO', max_length=20)),
                ('budget_tier', models.CharField(choices=[('BUDGET', 'Budget ($)'), ('MODERATE', 'Moderate ($$)'), ('LUXURY', 'Luxury ($$$)')], default='MODERATE', max_length=20)),
                ('preferred_currency', models.CharField(default='USD', max_length=10)),
                ('preferred_language', models.CharField(default='English', max_length=20)),
                ('is_admin_role', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WishlistDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlisted_by', to='destinations.city')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'city')},
            },
        ),
    ]
