# Generated by Django 5.1.1 on 2026-08-22 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, default='Passionate traveler exploring incredible destinations, mountain passes, and vibrant heritage.'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='budget_tier',
            field=models.CharField(choices=[('BUDGET', 'Budget (₹ / $)'), ('MODERATE', 'Moderate (₹₹ / $$)'), ('LUXURY', 'Luxury (₹₹₹ / $$$)')], default='MODERATE', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='preferred_currency',
            field=models.CharField(choices=[('INR', 'INR (₹ - Indian Rupee)'), ('USD', 'USD ($ - US Dollar)'), ('EUR', 'EUR (€ - Euro)'), ('GBP', 'GBP (£ - British Pound)'), ('AED', 'AED (د.إ - UAE Dirham)'), ('JPY', 'JPY (¥ - Japanese Yen)')], default='INR', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='preferred_language',
            field=models.CharField(default='English / Hindi', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='travel_style',
            field=models.CharField(choices=[('SOLO', 'Solo Explorer 🎒'), ('COUPLE', 'Romantic Getaway 💑'), ('FAMILY', 'Family Vacation 👨\u200d👩\u200d👧\u200d👦'), ('BACKPACKER', 'Backpacker / Budget 🏕️'), ('LUXURY', 'Luxury & Leisure ✨'), ('ADVENTURE', 'Adrenaline & Mountains 🏔️'), ('SPIRITUAL', 'Heritage & Spiritual 🛕')], default='SOLO', max_length=20),
        ),
    ]
