# Generated by Django 5.1.1 on 2026-08-22 07:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destinations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('estimated_budget', models.DecimalField(decimal_places=2, default=1500.0, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('cover_image_url', models.CharField(blank=True, default='https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=1200&auto=format&fit=crop&q=80', max_length=500)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='trip_covers/')),
                ('travel_style', models.CharField(choices=[('SOLO', 'Solo Explorer'), ('COUPLE', 'Couple Getaway'), ('FAMILY', 'Family Vacation'), ('BACKPACKER', 'Backpacker'), ('LUXURY', 'Luxury'), ('ADVENTURE', 'Adventure')], default='SOLO', max_length=20)),
                ('is_public', models.BooleanField(default=True)),
                ('share_slug', models.CharField(blank=True, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PLANNING', 'Planning'), ('UPCOMING', 'Upcoming'), ('ONGOING', 'In Progress'), ('COMPLETED', 'Completed')], default='PLANNING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cloned_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clones', to='trips.trip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TripCloneLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cloned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cloned_trips_log', to=settings.AUTH_USER_MODEL)),
                ('cloned_trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_history', to='trips.trip')),
                ('original_trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cloned_history', to='trips.trip')),
            ],
        ),
        migrations.CreateModel(
            name='TripComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='trips.tripcomment')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='trips.trip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TripExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('STAY', 'Accommodation'), ('TRANSPORT', 'Transportation'), ('ACTIVITY', 'Activities & Tickets'), ('MEAL', 'Food & Dining'), ('SHOPPING', 'Shopping & Gifts'), ('OTHER', 'Miscellaneous')], default='MEAL', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expense_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='trips.trip')),
            ],
            options={
                'ordering': ['-expense_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TripStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_date', models.DateField()),
                ('departure_date', models.DateField()),
                ('stop_order', models.PositiveIntegerField(default=1)),
                ('accommodation_name', models.CharField(blank=True, default='Boutique Hotel / Airbnb', max_length=200)),
                ('stay_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('transport_to_stop_type', models.CharField(choices=[('FLIGHT', 'Flight ✈️'), ('TRAIN', 'Train 🚆'), ('BUS', 'Bus 🚌'), ('CAR', 'Drive / Rental 🚗'), ('FERRY', 'Ferry ⛴️'), ('OTHER', 'Other 🚶')], default='FLIGHT', max_length=20)),
                ('transport_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_stops', to='destinations.city')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='trips.trip')),
            ],
            options={
                'ordering': ['stop_order', 'arrival_date'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('SIGHTSEEING', 'Sightseeing & Landmarks'), ('FOOD', 'Food & Culinary'), ('ADVENTURE', 'Adventure & Outdoors'), ('CULTURE', 'Culture & History'), ('RELAXATION', 'Relaxation & Wellness'), ('TRANSPORT', 'Transport & Transfer'), ('NIGHTLIFE', 'Nightlife & Drinks')], default='SIGHTSEEING', max_length=20)),
                ('scheduled_date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(default=120)),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('location', models.CharField(blank=True, max_length=250)),
                ('notes', models.TextField(blank=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('order_index', models.IntegerField(default=1)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_instances', to='destinations.activity')),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_activities', to='trips.tripstop')),
            ],
            options={
                'ordering': ['scheduled_date', 'order_index', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='TripLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='trips.trip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('trip', 'user')},
            },
        ),
        migrations.CreateModel(
            name='TripReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=5)),
                ('title', models.CharField(blank=True, max_length=150)),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='trips.trip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('trip', 'user')},
            },
        ),
    ]
