# Generated by Django 5.1.1 on 2026-08-22 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledactivity',
            name='category',
            field=models.CharField(choices=[('SIGHTSEEING', 'Sightseeing & Heritage 🏛️'), ('FOOD', 'Food & Culinary 🍲'), ('ADVENTURE', 'Trekking & Snow Adventure 🏔️'), ('CULTURE', 'Culture & Festivals 🪔'), ('SPIRITUAL', 'Temples & Spiritual 🛕'), ('RELAXATION', 'Lakes, Houseboats & Spas 🌿'), ('TRANSPORT', 'Transport & Transfers 🚆'), ('NIGHTLIFE', 'Night Markets & Cafes ☕')], default='SIGHTSEEING', max_length=20),
        ),
        migrations.AlterField(
            model_name='trip',
            name='currency',
            field=models.CharField(choices=[('INR', 'INR (₹ - Indian Rupee)'), ('USD', 'USD ($ - US Dollar)'), ('EUR', 'EUR (€ - Euro)'), ('GBP', 'GBP (£ - British Pound)'), ('AED', 'AED (د.إ - UAE Dirham)'), ('JPY', 'JPY (¥ - Japanese Yen)')], default='INR', max_length=10),
        ),
        migrations.AlterField(
            model_name='trip',
            name='estimated_budget',
            field=models.DecimalField(decimal_places=2, default=35000.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='trip',
            name='travel_style',
            field=models.CharField(choices=[('SOLO', 'Solo Explorer 🎒'), ('COUPLE', 'Romantic Getaway 💑'), ('FAMILY', 'Family Vacation 👨\u200d👩\u200d👧\u200d👦'), ('BACKPACKER', 'Backpacker / Roadtrip 🚗'), ('LUXURY', 'Luxury & Resorts ✨'), ('ADVENTURE', 'Trekking & Mountains 🏔️'), ('SPIRITUAL', 'Heritage & Pilgrimage 🛕')], default='SOLO', max_length=20),
        ),
        migrations.AlterField(
            model_name='tripexpense',
            name='category',
            field=models.CharField(choices=[('STAY', 'Accommodation'), ('TRANSPORT', 'Transportation & Fuel'), ('ACTIVITY', 'Activities & Entry Passes'), ('MEAL', 'Food, Thalis & Cafes'), ('SHOPPING', 'Handicrafts & Shopping'), ('OTHER', 'Miscellaneous')], default='MEAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='tripstop',
            name='accommodation_name',
            field=models.CharField(blank=True, default='Heritage Resort / Boutique Hotel', max_length=200),
        ),
        migrations.AlterField(
            model_name='tripstop',
            name='transport_to_stop_type',
            field=models.CharField(choices=[('FLIGHT', 'Flight ✈️'), ('TRAIN', 'Vande Bharat / Express Train 🚆'), ('BUS', 'Volvo / AC Bus 🚌'), ('CAR', 'Cab / Self-Drive / Rental 🚗'), ('SHIKARA', 'Shikara / Boat / Ferry ⛵'), ('OTHER', 'Other / Walk 🚶')], default='TRAIN', max_length=20),
        ),
    ]
